HALLOFLEGENDS_May_Text_Intro::
    .string "{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}MAY: So you're finally here,\n"
    .string "{PLAYER}.\p"
    .string "I'm MAY, I'm from HOENN.\p"
    .string "I came to KANTO with BRENDAN,\n"
    .string "after hearing about a genius\p"
    .string "TRAINER that shut down TEAM\n"
    .string "ROCKET and became the CHAMPION\p"
    .string "in no time at all.\p"
    .string "Let's battle, {PLAYER}.\n"
    .string "I may not be the HOENN CHAMPION,\p"
    .string "but I'll show you just how\n"
    .string "powerful HOENN's No.2 is!$"

HALLOFLEGENDS_May_Text_Defeat::
    .string "Ah, I lost...\n"
    .string "You're really strong, {PLAYER}!$"

HALLOFLEGENDS_May_Text_PostBattle::
    .string "MAY: So the rumors were true!\n"
    .string "It was a beautiful and fun\p"
    .string "battle, {PLAYER}!\p"
    .string "BRENDAN wants to fight you\n"
    .string "as well! Go straight ahead.$"

HALLOFLEGENDS_Brendan_Text_Intro::
    .string "{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}BRENDAN: So you defeated MAY,\n"
    .string "huh? Nice to meet you, {PLAYER}.\p"
    .string "I'm BRENDAN, the HOENN CHAMPION.\n"
    .string "I came to KANTO with MAY\p"
    .string "to meet you, the rising star\n"
    .string "of KANTO. Let's see who's stronger\p"
    .string "between the KANTO and HOENN\n"
    .string "champions, yeah? Our battle\p"
    .string "will be engraved in history!\n"
    .string "Let's go!$"

HALLOFLEGENDS_Brendan_Text_Defeat::
    .string "A true display of skill.\p"
    .string "You and your POKéMON\n"
    .string "were incredible!$"

HALLOFLEGENDS_Brendan_Text_PostBattle::
    .string "BRENDAN: I never thought the day\n"
    .string "I lost a battle would come.\p"
    .string "I traveled far and wide\n"
    .string "and won countless battles,\p"
    .string "but you're special, {PLAYER}.\p"
    .string "You are the strongest\n"
    .string "TRAINER in the world!$"
