name: CI

on:
  push:
    branches: [ rando ]

jobs:
  jar:
    uses: champred/UPR-Android/.github/workflows/jar.yml@master
  build:
    runs-on: ubuntu-latest
    env:
      GAME_VERSION: FIRERED
      GAME_LANGUAGE: ENGLISH
      GAME_REVISION: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install binutils
        run: sudo apt install gcc-arm-none-eabi binutils-arm-none-eabi libcapstone-dev
        # build-essential, git, and libpng-dev are already installed
        # gcc-arm-none-eabi is only needed for the modern build
        # as an alternative to dkP

      - name: Install agbcc
        run: |
          ./build.sh
          ./install.sh ../pokefirered
        working-directory: ./agbcc

      - name: Build ROM
        run: make -j${nproc} all syms
        working-directory: ./pokefirered

      - name: Download JAR
        uses: actions/download-artifact@v4
        with:
          name: JAR

      - name: Generate Offsets
        run: |
          chmod +x offgen.sh
          ./offgen.sh
          cp ../upr.jar dist
        working-directory: ./pokefirered

      - name: Upload Files
        uses: actions/upload-artifact@v4
        with:
          name: Dist
          path: pokefirered/dist
